export const whiteTheme = {
	bgColor: "#f4f2f2",
	bgApp: "#fff",
	bgDetail: "#fdfdfd",
	bgSlide: "#cccccc",
	bgContact: "#d9ebf2",
	bgContactSelect: "#85cde3",
	bgInfoUser: "#b1b9ea",
	bgSended: "#b7ece7",
	bgReceived: "#ccc",
	bgInput: "#a8ed8982",
	bgEmoji: "#eee",
	bgToggleButton: "#fff",
	bgEmojiHover: "#ccc",
	color: "#000",
	colorButton: "transparent",
	colorButtonHover: "#d9ebf2",
	colorSvg: "#626161",
	colorMsg: "#000",
	colorEmoji: "#e0e01b",
	colorEmojiHover: "#a5a511",
	colorLabelEmoji: "#4c4949",
	colorName: "#4e0eff",
	borderColorEmoji: "#9186f3",
	borderApp: "1px solid #ccc",
};
